### ISSUE TITLE
Cannot read property 'count' of undefined

### ISSUE THREAD

**Issue by sarus** [polarityio/alienvault-otx#5]
```
{
    "debug": {
        "stderr": "\nStacktrace:\n====================\nTypeError: Cannot read property 'count' of undefined\n    at Request._callback (/app/polarity-server/integrations/alienvault-otx/integration.js:227:74)\n    at Request.self.callback (/app/polarity-server/integrations/alienvault-otx/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/app/polarity-server/integrations/alienvault-otx/node_modules/request/request.js:1060:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/app/polarity-server/integrations/alienvault-otx/node_modules/request/request.js:980:12)\n    at IncomingMessage.g (events.js:292:16)\n    at emitNone (events.js:91:20)\n\n"
    },
    "md5": "bc31b399ead534b2cbb271ec5e258d7d"
}
```

**Comment by sarus** [comment]
Fixed in the 3.0.0 release
